#!/usr/bin/env bash
#comment
sudo apt-get update
sudo apt-get install nginx
echo "<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
" > /var/www/html/index.html
service nginx start
