#!/usr/bin/env bash
#comment
docker run -p 8080:80 -d -it --name holberton-container holbertonschool/265-0 /bin/bash
docker exec -it holberton-container /bin/bash
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
exit
curl 0:8080
