#!/usr/bin/env bash
#comment
docker run -p 8080:80 -d -it holbertonschool/265-0 /bin/bash
docker exec -it <container_id> /bin/bas
apt-get update
apt-get install -y apache2
sudo echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
curl 0:8080
